Ensure that check-changes step passed

diff --git a/.github/workflows/pr-tests.yml b/.github/workflows/pr-tests.yml
--- a/.github/workflows/pr-tests.yml
+++ b/.github/workflows/pr-tests.yml
@@ -130,6 +130,10 @@ jobs:
             echo "Lint/security checks failed"
             exit 1
           fi
+          if [[ "${{ needs.check-changes.result }}" == "failure" ]]; then
+            echo "Change detection failed"
+            exit 1
+          fi
           if [[ "${{ needs.test-iac.result }}" == "failure" ]]; then
             echo "Tests failed"
             exit 1
